language: node_js
sudo: false
node_js:
  - 6
notifications:
  webhooks: https://www.travisbuddy.com/
  on_success: never
before_script:
  - npm install -g free-programming-books-lint
script: fpb-lint .
